# Site settings
name: Brittany Chiang
title: Niyati Jain | Data Engineer
description: Data Engineer based in New Brunswick, NJ
url: https://niyatijain21.github.io/
baseurl: ""
email: niyatijain2104@gmail.com
cover: img/og.png
logo: img/logo/logo1.png
resume: resume.pdf
social:
  - title: email
    url: mailto:niyatijain2104@gmail.com
  - title: github
    url: https://github.com/niyatijain21
  - title: linkedin
    url: https://linkedin.com/in/niyatijain21

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
